# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/raw/server.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Server(object):
    def setupUi(self, Server):
        Server.setObjectName("Server")
        Server.resize(652, 546)
        self.centralwidget = QtWidgets.QWidget(Server)
        self.centralwidget.setObjectName("centralwidget")
        self.user_table = QtWidgets.QTableView(self.centralwidget)
        self.user_table.setGeometry(QtCore.QRect(10, 190, 631, 271))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_table.sizePolicy().hasHeightForWidth())
        self.user_table.setSizePolicy(sizePolicy)
        self.user_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.user_table.setShowGrid(True)
        self.user_table.setObjectName("user_table")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 30, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 60, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 0, 101, 16))
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 140, 661, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.ipv4_host_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ipv4_host_input.setGeometry(QtCore.QRect(130, 30, 113, 21))
        self.ipv4_host_input.setObjectName("ipv4_host_input")
        self.ipv6_host_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ipv6_host_input.setGeometry(QtCore.QRect(450, 30, 113, 21))
        self.ipv6_host_input.setObjectName("ipv6_host_input")
        self.port_input = QtWidgets.QLineEdit(self.centralwidget)
        self.port_input.setGeometry(QtCore.QRect(130, 60, 61, 21))
        self.port_input.setObjectName("port_input")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(240, 100, 81, 32))
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(330, 100, 81, 32))
        self.stop_button.setObjectName("stop_button")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 160, 71, 16))
        self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_3.setObjectName("label_3")
        self.connection_counter = QtWidgets.QLabel(self.centralwidget)
        self.connection_counter.setGeometry(QtCore.QRect(20, 470, 81, 16))
        self.connection_counter.setObjectName("connection_counter")
        Server.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Server)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 652, 24))
        self.menubar.setObjectName("menubar")
        Server.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Server)
        self.statusbar.setObjectName("statusbar")
        Server.setStatusBar(self.statusbar)

        self.retranslateUi(Server)
        QtCore.QMetaObject.connectSlotsByName(Server)

    def retranslateUi(self, Server):
        _translate = QtCore.QCoreApplication.translate
        Server.setWindowTitle(_translate("Server", "MainWindow"))
        self.label_2.setText(_translate("Server", "IPv4 address:"))
        self.label_4.setText(_translate("Server", "IPv6 address:"))
        self.label_6.setText(_translate("Server", "Port:"))
        self.label.setText(_translate("Server", "*Server settings*"))
        self.ipv4_host_input.setText(_translate("Server", "127.0.0.1"))
        self.ipv6_host_input.setText(_translate("Server", "::1"))
        self.port_input.setText(_translate("Server", "65432"))
        self.start_button.setText(_translate("Server", "Start"))
        self.stop_button.setText(_translate("Server", "Stop"))
        self.label_3.setText(_translate("Server", "*User base*"))
        self.connection_counter.setText(_translate("Server", "Connections"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Server = QtWidgets.QMainWindow()
    ui = Ui_Server()
    ui.setupUi(Server)
    Server.show()
    sys.exit(app.exec_())
